### ISSUE TITLE
Mark non-characters as specials

### ISSUE THREAD

**Issue by Mercury13** [notofonts/overview#10]
### Title 
Non-characters (e.g. FFFE, FFFF) are red.

### Issue
Non-characters FFFE, FFFF and so on are red. Indeed, no one supports them, but should they? It’s better to paint then black.

### Character data
FFFE, FFFF non-characters
FDD0…FDEF non-characters

### Screenshot
![image](https://user-images.githubusercontent.com/10164882/193516769-632c0381-31f2-4929-8cfc-f24699af86d2.png)

**Comment by simoncozens** [comment]
This is the same as #8, I think.
