### ISSUE TITLE
Add color legend

### ISSUE THREAD

**Issue by davelab6** [notofonts/overview#3]
@marekjez86 said in chat room, 

> Simon, would it make sense to add a tiny color legend somewhere (feel free to rewrite/correct my wording)?
> 
> Color Legend:
> 
> Black (no Noto font should have glyphs for it; control or special characters)
> 
> Dark green (more than one Noto font includes this codepoint)
> 
> Light green (one font includes this codepoint)
> 
> Grey (unassigned codepoint)
> 
> Red (Noto does have glyphs for it. Outside of CJK fonts, means an opportunity to fill the "coverage hole", but for CJK usually means "we have no room in the font file to include this character.")

This is a key feature :)

**Comment by simoncozens** [comment]
Closed in c33ea56. (GitHub was having a sad while I pushed it.)
