### ISSUE TITLE
Dynamically request fonts

### ISSUE THREAD

**Issue by simoncozens** [notofonts/overview#5]
> Currently I don't use any web fonts, so it only shows glyphs with the fonts you have installed. I suppose it would be possible (and very cool) to dynamically add CSS font-face statements for the detail boxes so that you're served the fonts needed to display each block.

**Comment by mi2ebi** [comment]
doesn't work for me (ios 17.2)
![image](https://github.com/notofonts/overview/assets/50974538/0c82ac08-3195-4929-9ed2-a3660bbcb3ef)
